version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./backend
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    env_file:
      - ./backend/.env.docker
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
      - /app/node_modules
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/appA
      - /app/node_modules
    depends_on:
      - api

volumes:
  mongo_data:
  uploads:
